### ISSUE TITLE
Implement scope Header

### ISSUE THREAD

**Issue by offa** [offa/scope-guard#32]
Implement `scope` Header as described in § 7.5.1.

### Classes

- [x] `scope_exit` – #33
- [x] `scope_fail` – #34
- [x] `scope_success` – #35
- [x] `unique_resource` – #37

### Factories

- [x] `make_unique_resource_checked()` – #39
- [x] `make_scope_exit()` – #36 
- [x] `make_scope_fail()` – #36 
- [x] `make_scope_success()` – #36 
- [x] `make_unique_resource()` – #39
